# Generated by Django 5.2.1 on 2025-06-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_item',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='The date at which the checklist item was edited if ther is one'),
        ),
    ]
