# Generated by Django 5.2.1 on 2025-05-30 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, verbose_name='The task to be completed for this checklist item.')),
                ('description', models.TextField(verbose_name='Long description of what the task is')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='The date and time that the item was created')),
                ('is_complete', models.BooleanField(verbose_name='Has the task been completed or not')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
