# Generated by Django 5.2.1 on 2025-06-11 06:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_checklist_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(null=True, verbose_name="The user's primary address"),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(null=True, verbose_name="The user's secondary address"),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
