# Generated by Django 5.2.1 on 2025-05-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_checklist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_item',
            name='description',
            field=models.TextField(null=True, verbose_name='Long description of what the task is'),
        ),
        migrations.AlterField(
            model_name='checklist_item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
